# HLint configuration file
# https://github.com/ndmitchell/hlint

# Ignore some builtin hints
# - ignore: {name: Use let}
# - ignore: {name: Use const, within: SpecialModule} # Only within certain modules
- ignore: {name: "Use newtype instead of data"}
- ignore: {name: "Redundant bracket"}
- ignore: {name: "Redundant do"}
- ignore: {name: "Avoid lambda"}
- ignore: {name: "Eta reduce"}
- ignore: {name: "Move brackets to avoid $"}
- ignore: {name: "Avoid lambda using `infix`"}
- ignore: {name: "Replace case with maybe"}
- ignore: {name: "Redundant return"}
- ignore: {name: "Use notElem"}
- ignore: {name: "Use if"}
- ignore: {name: "Use maybe"}
- ignore: {name: "Use tuple-section"}
- ignore: {name: "Use infix"}
