name: Erlang CI

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        erlang: [ 25,26 ]

    container:
      image: erlang:${{ matrix.erlang }}

    steps:
    - uses: actions/checkout@v2
    - run: ./rebar3 compile

  test:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        erlang: [ 25,26 ]

    container:
      image: erlang:${{ matrix.erlang }}

    steps:
    - uses: actions/checkout@v2
    - run: ./rebar3 eunit -m minsem
    - run: ./rebar3 proper -n 1000

  verify:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        erlang: [ 26 ]

    container:
      image: erlang:${{ matrix.erlang }}

    steps:
    - uses: actions/checkout@v2
    - name: Dialyzer
      run: ./rebar3 dialyzer
